version: '3.8'

services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "5002:5002"
    volumes:
      - ./lms/static/uploads:/app/lms/static/uploads
      - ./instance:/app/instance
    environment:
      - FLASK_APP=app.py
      - SECRET_KEY=your-secret-key-here
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/lms
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=adminpassword
    depends_on:
      - db
    command: python app.py

  db:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=lms
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: