version: '3.8'

services:
  web:
    build: .
    restart: always
    ports:
      - "5002:5002"
    volumes:
      - ./lms/static/uploads:/app/lms/static/uploads
      - ./instance:/app/instance
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -c "python -c 'import time; time.sleep(5)' &&
             python setup_db.py &&
             gunicorn --bind 0.0.0.0:5002 app:app"

  db:
    image: postgres:14
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-lms}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: